version: '3.8'

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: douabaghdadi
      MYSQL_DATABASE: achatdb
      MYSQL_USER: achatuser
      MYSQL_PASSWORD: userpassword

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: achat-backend-douabaghdadi-4twin9
    depends_on:
      - mysql-container
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: achatuser
      SPRING_DATASOURCE_PASSWORD: userpassword
    entrypoint: ["sh", "-c", "until nc -z -v -w30 mysql-container 3306; do echo 'Waiting for MySQL...'; sleep 5; done; java -jar app.jar"]